version: "3"
services:
    x2e_ref-dev:
        build:
            context: ./build_context
        hostname: x2e_ref-dev
        volumes:
            - ../working:/working
            - ./home:/home
            - ./opt:/opt
            - ./archives:/archives
        working_dir: /working
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "5"
        user: ${CURRENT_USER}
        privileged: true

networks:
    default:
        external:
            name: docker99
